services:
  migration:
    build:
      context: .
      dockerfile: LostDogApp/dev.Dockerfile
    command: ["dotnet", "ef", "database", "update", "--connection", "Host=postgres;Port=5432;Database=lostdogapp;Username=lostdog;Password=password"]
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge